
### api calls for our blog post API

GET http://localhost:3000 HTTP/1.1

### GET all blog posts

GET http://localhost:3000/api/blogposts/ HTTP/1.1

### Get a blog post by ID

GET http://localhost:3000/api/blogposts/13 HTTP/1.1